# Generated by Django 5.1.1 on 2024-09-11 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                
                ('nivel_dolor', models.IntegerField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.paciente')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.especialidad')),
            ],
        ),
    ]
