# Generated by Django 5.1.1 on 2024-09-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='nivel_dolor',
            new_name='nivel_dolor',
        ),
    ]
