# Generated by Django 5.1.1 on 2024-09-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0002_rename_apellidos_paciente_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='cedula',
            new_name='cedula_id',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='especialidad',
            new_name='especialidad_id',
        ),
    ]
