# Generated by Django 5.1.1 on 2024-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0004_rename_cedula_id_solicitud_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
