# Generated by Django 5.1.1 on 2024-09-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0005_alter_solicitud_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='id',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cedula',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
    ]
